# Generated by Django 4.1.1 on 2022-09-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(verbose_name='Submit Time')),
                ('status', models.CharField(choices=[('SUB', 'Submitted'), ('WAIT', 'Waiting'), ('RUN', 'Running'), ('FIN', 'Finished'), ('ERR', 'Error occurred'), ('UNK', 'Unknown status')], max_length=4)),
                ('result', models.TextField(max_length=1000)),
            ],
        ),
    ]
