# Generated by Django 4.1.1 on 2022-09-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0002_alter_testrun_result_alter_testrun_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='submitter_id',
            field=models.CharField(default=-1, max_length=12, verbose_name='ID of submitter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrun',
            name='submitter_name',
            field=models.CharField(default=-1, max_length=20, verbose_name='Name of Submitter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('SUB', 'Submitted'), ('WAIT', 'Waiting'), ('RUN', 'Running'), ('FIN', 'Finished'), ('ERR', 'Error occurred'), ('UNK', 'Unknown status')], default='SUB', max_length=4, verbose_name='Status'),
        ),
    ]
