# Generated by Django 4.1.2 on 2022-10-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0005_testrun_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('WAIT', 'Waiting'), ('RUN', 'Running'), ('FIN', 'Finished'), ('ERR', 'Error occurred'), ('UNK', 'Unknown status')], default='WAIT', max_length=4, verbose_name='Status'),
        ),
    ]
