# Generated by Django 4.1.2 on 2022-10-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0006_alter_testrun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='image_name',
            field=models.CharField(max_length=200, verbose_name='Image name'),
        ),
    ]
