# Generated by Django 4.1.2 on 2022-10-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0007_alter_testrun_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='runner_id',
            field=models.CharField(default='None', max_length=100, verbose_name='Runner ID'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('ERROR', 'Error occurred'), ('UNKKNOWN', 'Unknown status'), ('RETRYING', 'Retrying')], default='WAITING', max_length=10, verbose_name='Status'),
        ),
    ]
