# Generated by Django 4.1.2 on 2022-10-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0008_testrun_runner_id_alter_testrun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('ERROR', 'Error occurred'), ('UNKKNOWN', 'Unknown status'), ('RETRYING', 'Retrying')], default='SUBMITTED', max_length=10, verbose_name='Status'),
        ),
    ]
