# Generated by Django 4.1.2 on 2022-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0010_testrun_log_testrun_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='testrun_type',
            field=models.CharField(default='Sim', max_length=10, verbose_name='Type'),
        ),
    ]
