# Generated by Django 4.1.2 on 2022-11-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0011_testrun_testrun_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='log',
        ),
    ]
