# Generated by Django 4.1.2 on 2022-11-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0012_remove_testrun_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='log_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
