# Generated by Django 4.1.2 on 2022-12-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0013_testrun_log_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='another_log_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrun',
            name='run_type',
            field=models.IntegerField(default=1, verbose_name='Run Type'),
            preserve_default=False,
        ),
    ]
