# Generated by Django 4.1.2 on 2022-12-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0014_testrun_another_log_file_testrun_run_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('ERROR', 'Error occurred'), ('UNKKNOWN', 'Unknown status'), ('RETRYING', 'Retrying'), ('CRASH', 'Crash')], default='SUBMITTED', max_length=10, verbose_name='Status'),
        ),
    ]
