# Generated by Django 4.1.2 on 2022-12-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger', '0016_testrun_digest_testrun_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('WAITING', 'Waiting'), ('RUNNING', 'Running'), ('FINISHED', 'Finished'), ('ERROR', 'Error occurred'), ('UNKKNOWN', 'Unknown status'), ('RETRYING', 'Retrying'), ('CRASH', 'Crash'), ('TIMEOUT', 'TIMEOUT')], default='SUBMITTED', max_length=10, verbose_name='Status'),
        ),
    ]
